### PR TITLE
🚀[Feat]: Adding Theme Selection

### LINKED ISSUE #2: Add themes to editor
The current editor uses only one default theme `material`.Add a dropdown menu, for the users to select multiple theme options.

### PR DESCRIPTION
**Pull request by JoalbertMilano**
Fixes #7 
Desc: fixed issue "**Add themes to editor**"

### CODE REVIEW

**Review by KshitijDarekar — COMMENTED** [review]
Great Work @JoalbertMilano !! Could you check why there are so many changes in package-lock.json file . Also , it would be great if you include a dropdown icon in the theme selection to improve the design.

**Comment by KshitijDarekar** [comment]
Hey @JoalbertMilano   why don't you try registering in OpenCode and then start contributing to this and other issues? The registration is completely free and there are a lot of stuff like certificates and goodies in the room for participants..!
You can register through the registration form at the official website:
https://csirait.in/opencode/

**Comment by JoalbertMilano** [comment]
@KshitijDarekar i was using `npm install` commad to install dependencies and that update the package.lock.json, i start using `npm ci` commad and it works to no update the package.lock.json when install, i commit again fixing the changes in the .lock and adding the dropdown icon you suggested

**Review by KshitijDarekar — APPROVED** [review]
LGTM 🚀

**Comment by KshitijDarekar** [comment]
@JoalbertMilano we are good to merge the PR. Just edit the PR description and mention the issue which is fixed, for future references.

**Comment by JoalbertMilano** [comment]
> @JoalbertMilano we are good to merge the PR. Just edit the PR description and mention the issue which is fixed, for future references.

done

**Comment by JoalbertMilano** [comment]
> @JoalbertMilano we are good to merge the PR. Just edit the PR description and mention the issue which is fixed, for future references.

done

**Pull request merged**
